# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      dev-tools:
        patterns:
          - "pytest*"
          - "ruff*"
          - "mypy*"
          - "pre-commit*"
          - "pip-audit*"
          - "bandit*"
          - "hypothesis*"
          - "mkdocs*"
          - "pytest-xdist*"
          - "pymdown*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      actions:
        patterns: ["*"]
